# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Advanced Counceling
email: EMAIL
description: > This website is the website for the counseling service in PA PLEASE CHANGE THIS LATER TO SOMETHING BETTER BECAUSE THIS WILL APPEAR ON GOOGLE ONCE THE SITE IS LIVE AND SEARCHED FOR # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.advanced-counseling.com/" # the base hostname & protocol for your site
twitter_username:
github_username:
# Build settings
markdown: kramdown
